// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddReviewInListController from "./add_review_in_list_controller"
application.register("add-review-in-list", AddReviewInListController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
